services:
  - type: web
    name: number-storage
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb://localhost:27017/numberdb
      # Add more environment variables as needed
